@host = http://localhost:8100
@host = https://todo-api-x0p3.onrender.com


### GET /
GET {{host}}/


### GET TODOS
GET {{host}}/todos

### POST TODO
POST {{host}}/todos
Content-Type: application/json

{
  "title": "First Task",
  "completed": false
} 

### UPDATE TODO
PUT {{host}}/todos/1
Content-Type: application/json

{
  "title": "Updated Task",
  "completed": false
}

### PATCH TODO
PATCH {{host}}/todos/1
Content-Type: application/json

{
  "completed": true
}