# @host = http://localhost:10000
@host = https://todo-api-a2l5.onrender.com


### GET HOME
GET {{host}}/


### GET TODOS
GET {{host}}/todos

### POST TODO
POST {{host}}/todos
Content-Type: application/json

{
  "title": "Second Task",
  "completed": false
} 

### UPDATE TODO
PUT {{host}}/todos/1
Content-Type: application/json

{
  "title": "Updated Task",
  "completed": false
}

### PATCH TODO
PATCH {{host}}/todos/2
Content-Type: application/json

{
  "completed": true
}

### DELETE TODO
DELETE {{host}}/todos/2